import = ['~\.config\alacritty\catppuccin-mocha.toml']
shell = 'C:\Program Files\PowerShell\7-preview\pwsh.exe'

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "Iosevka NFM"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka NFM"
style = "Italic"

[font.normal]
family = "Iosevka NFM"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 15000

[window]
opacity = 0.9
dynamic_padding = true
decorations = "Full"

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"
