---@type LazySpec
return {
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    opts = {
      ensure_installed = {
        "lua-language-server",
        "stylua",
        "debugpy",
        "tree-sitter-cli",
        "bash-language-server",
        "shellcheck",
        "shfmt",
        "bash-debug-adapter",
        "clangd",
        "codelldb",
        "clang-format",
        "gopls",
        "delve",
        "goimports",
        "gofumpt",
        "golangci-lint",
        "pyright",
        "ruff",
        "black",
        "rust-analyzer",
        "texlab",
        "typescript-language-server",
        "eslint-lsp",
        "eslint_d",
        "prettierd",
        "json-lsp",
        "taplo",
        "dockerfile-language-server",
        "docker-compose-language-service",
        "marksman",
        "lemminx",
        "markdownlint",
        "yaml-language-server",
        "yamllint",
      },
    },
  },
}
